### ISSUE TITLE
wordcloud installation error

### ISSUE THREAD

**Issue by minkyawzaw** [conda-forge/wordcloud-feedstock#15]
Issue: I am using window 8.1 version 32-bites. When I install wordcloud I found two things.  1. it redownload existing file again. 2.it download low version than existing one(e.g. python 3.7.0, pip 18.0 it redownload 3.6.5, 10.0). why don't download only require file. 

it downloaded wordcloud-1.4.1-py36 version for win-32.
Finally, it show installation error.

<br/>
Environment (<code>conda list</code>):
<details>

_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
alabaster                 0.7.12                     py_0    conda-forge
altair                    2.2.2                     <pip>
anaconda                  custom                   py37_0
anaconda-client           1.7.1                      py_0    conda-forge
anaconda-navigator        1.9.2                    py37_0
anaconda-project          0.8.2                      py_1    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                   py37_0
astroid                   2.0.2                    py37_0
astropy                   3.0.5            py37he774522_0
atomicwrites              1.2.1                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
automat                   0.7.0                      py_1    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forg
e
beautifulsoup4            4.6.3                    py37_0
bitarray                  0.8.3            py37hfa6e2cd_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl    conda-forge
blaze                     0.11.3                   py37_0
bleach                    3.0.2                      py_0    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.14.4               he51fdeb_0
bokeh                     1.0.0                    py37_0
boto                      2.49.0                   py37_0
boto3                     1.9.32                     py_0    conda-forge
botocore                  1.12.33                    py_0    conda-forge
bottleneck                1.2.1            py37h452e1ab_1
branca                    0.3.0                     <pip>
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.6                    vc14_1  [vc14]  conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.10.15               py37_0
cffi                      1.11.5           py37h74b6da3_1
chardet                   3.0.4                      py_1    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               0.6.1                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.0                      py_0    conda-forge
comtypes                  1.1.7                    py37_0
conda                     4.5.11                   py37_0
conda-build               3.16.1                   py37_0
conda-env                 2.6.0                         1    conda-forge
console_shortcut          0.1.1                         3
constantly                15.1.0                     py_0    conda-forge
contextlib2               0.5.5                      py_2    conda-forge
cryptography              2.3              py37h74b6da3_1
cryptography-vectors      2.3.1                    py37_0
curl                      7.49.1                   vc14_2  [vc14]  conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29             py37ha925a31_0
cytoolz                   0.9.0.1          py37hfa6e2cd_1
dask                      0.20.0                     py_0    conda-forge
dask-core                 0.20.0                     py_0    conda-forge
datashape                 0.5.4                    py37_1
decorator                 4.3.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
distributed               1.23.3                   py37_0
docutils                  0.14                     py37_0
entrypoints               0.2.3                    py37_2
et_xmlfile                1.0.1                    py37_0
fastcache                 1.0.2            py37hfa6e2cd_2
filelock                  3.0.9                      py_0    conda-forge
flask                     1.0.2                      py_2    conda-forge
flask-cors                3.0.6                      py_0    conda-forge
folium                    0.6.0                     <pip>
freetype                  2.9.1                ha9979f8_1
gensim                    3.4.0            py37hfa6e2cd_0
geographiclib             1.49                      <pip>
geopy                     1.17.0                    <pip>
get_terminal_size         1.0.0                h4b36c58_0
gevent                    1.3.7            py37he774522_1
glob2                     0.6                        py_0    conda-forge
gpxpy                     1.3.4                     <pip>
greenlet                  0.4.15           py37hfa6e2cd_0
h5py                      2.8.0            py37h3bdd7fb_2
hdf5                      1.10.2               hac2f561_2
heapdict                  1.0.0                    py37_2
html5lib                  1.0.1                      py_0    conda-forge
hyperlink                 17.3.1                     py_0    conda-forge
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 h3fcc66b_1
idna                      2.7                        py_1    conda-forge
imageio                   2.3.0                      py_1    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
importlib_metadata        0.5                        py_0    conda-forge
incremental               17.5.0                     py_0    conda-forge
intel-openmp              2019.0                      118
ipykernel                 5.1.0              pyh24bf2e0_0    conda-forge
ipython                   7.0.1            py37h39e3cac_0
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isort                     4.3.4                    py37_0
itsdangerous              1.1.0                      py_0    conda-forge
jdcal                     1.4                        py_1    conda-forge
jedi                      0.13.1                   py37_0
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9b                       vc14_1  [vc14]  conda-forge
jsonschema                2.6.0                    py37_0
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.2                   py37_0
jupyterlab_launcher       0.13.1                     py_2    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
keyring                   15.1.0                   py37_0
kiwisolver                1.0.1            py37h6538335_0
lazy-object-proxy         1.3.1            py37hfa6e2cd_2
libarchive                3.3.2                h843f8d1_5
libcurl                   7.61.1               h2a8f88b_0
libiconv                  1.15                 hc4a7105_7
libpng                    1.6.35               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libssh2                   1.8.0                    vc14_1  [vc14]  conda-forge
libtiff                   4.0.9                h36446d0_2
libxml2                   2.9.8                hadb2253_1
libxslt                   1.1.32               hf6f1972_0
llvmlite                  0.25.0                   py37_0
locket                    0.2.0                      py_2    conda-forge
lxml                      4.2.5            py37hef2cd61_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h00ab751_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.0              py37hfa6e2cd_1
matplotlib                3.0.1            py37hc8f65d3_0
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.14           py37hfa6e2cd_0
mistune                   0.8.3                      py_0    conda-forge
mkl                       2019.0                      118
mkl-service               1.1.2            py37hb217b18_5
mkl_fft                   1.0.6            py37hdbbee80_0
mkl_random                1.0.1            py37h77b88f5_1
more-itertools            4.2.0                      py_0    conda-forge
mplleaflet                0.0.5                     <pip>
mpmath                    1.0.0                      py_1    conda-forge
msgpack-python            0.5.6            py37he980bc4_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                      py_0    conda-forge
navigator-updater         0.2.1                    py37_0
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
networkx                  2.2                        py_1    conda-forge
nltk                      3.2.5                      py_0    conda-forge
nose                      1.3.7                    py37_2
notebook                  5.7.0                    py37_0
numba                     0.40.0           py37hf9181ef_0
numexpr                   2.6.8            py37h9ef55f4_0
numpy                     1.15.3           py37ha559c80_0
numpy-base                1.15.3           py37h8128ebf_0
numpydoc                  0.8.0                      py_1    conda-forge
oauthlib                  2.1.0                      py_0    conda-forge
odo                       0.5.1                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openpyxl                  2.5.9                      py_0    conda-forge
openssl                   1.0.2o                   vc14_0  [vc14]  conda-forge
packaging                 18.0                       py_0    conda-forge
pandas                    0.23.4           py37h830ac7b_0
pandoc                    2.1.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
path.py                   11.5.0                     py_0    conda-forge
pathlib2                  2.3.2                    py37_0
patsy                     0.5.1                      py_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pickleshare               0.7.5                    py37_0
pillow                    5.3.0            py37hdc69c19_0
pip                       18.1                      <pip>
pip                       10.0.1                   py37_0
pkginfo                   1.4.2                      py_1    conda-forge
plotly                    3.3.0                     <pip>
pluggy                    0.8.0                      py_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.4.2                      py_0    conda-forge
prompt_toolkit            2.0.6                      py_0    conda-forge
psutil                    5.4.7            py37hfa6e2cd_0
py                        1.7.0                      py_0    conda-forge
pyasn1                    0.4.4                      py_1    conda-forge
pyasn1-modules            0.2.1                      py_0    conda-forge
pycodestyle               2.4.0                      py_1    conda-forge
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.19                       py_0    conda-forge
pycrypto                  2.6.1            py37hfa6e2cd_9
pycurl                    7.43.0.2         py37h74b6da3_0
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyhamcrest                1.9.0                      py_2    conda-forge
pyjwt                     1.6.4                      py_0    conda-forge
pylint                    2.1.1                    py37_0
pyodbc                    4.0.24           py37h6538335_0
pyopenssl                 18.0.0                   py37_0
pyparsing                 2.2.2                      py_0    conda-forge
pyqt                      5.9.2            py37h6538335_0
pysocks                   1.6.8                    py37_0
pytables                  3.4.4            py37he6f6034_0
pytest                    3.2.2                      py_0    conda-forge
pytest-arraydiff          0.2                        py_0    conda-forge
pytest-astropy            0.4.0                      py_0    conda-forge
pytest-doctestplus        0.1.3                      py_0    conda-forge
pytest-openfiles          0.3.0                      py_0    conda-forge
pytest-remotedata         0.3.0                      py_0    conda-forge
python                    3.7.1                h33f27b4_3
python-crfsuite           0.9.6            py37h6538335_0
python-dateutil           2.7.4                      py_0    conda-forge
python-libarchive-c       2.8                      py37_6
pytz                      2018.6                     py_0    conda-forge
pywaffle                  0.1.0                     <pip>
pywavelets                1.0.1            py37h8c2d366_0
pywin32                   223              py37hfa6e2cd_1
pywinpty                  0.5.4                    py37_0
pyyaml                    3.13             py37hfa6e2cd_0
pyzmq                     17.1.2           py37hfa6e2cd_0
qt                        5.9.6            vc14h62aca36_0
qtawesome                 0.5.2              pyh8a2030e_0    conda-forge
qtconsole                 4.4.2                      py_1    conda-forge
qtpy                      1.5.2              pyh8a2030e_0    conda-forge
requests                  2.19.1                   py37_0
requests-oauthlib         1.0.0                      py_1    conda-forge
retrying                  1.3.3                     <pip>
rope                      0.10.7                     py_1    conda-forge
ruamel_yaml               0.15.46          py37hfa6e2cd_0
s3transfer                0.1.13                   py37_0
scikit-image              0.14.0           py37h6538335_1
scikit-learn              0.20.0           py37heebcf9a_1
scipy                     1.1.0            py37h4f6bf74_1
seaborn                   0.9.0                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
service_identity          17.0.0                     py_0    conda-forge
setuptools                40.4.3                   py37_0
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h6538335_0
six                       1.11.0                   py37_1
smart_open                1.7.1                      py_0    conda-forge
snappy                    1.1.7                    vc14_1  [vc14]  conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcollections         1.0.1                      py_1    conda-forge
sortedcontainers          2.0.5                      py_0    conda-forge
sphinx                    1.8.1                    py37_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
spyder                    3.3.1                    py37_1
spyder-kernels            0.2.6                      py_1    conda-forge
sqlalchemy                1.2.12           py37he774522_0
sqlite                    3.25.2               hfa6e2cd_0
statsmodels               0.9.0            py37h452e1ab_0
sympy                     1.3                      py37_0
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                    py37_1
testpath                  0.4.2                    py37_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1            py37hfa6e2cd_0
tqdm                      4.28.1                     py_0    conda-forge
traitlets                 4.3.2                    py37_0
twisted                   18.9.0           py37he774522_0
twython                   3.7.0                      py_0    conda-forge
typing                    3.6.6                     <pip>
unicodecsv                0.14.1                     py_1    conda-forge
urllib3                   1.23                     py37_0
vc                        14.1                 h0510ff6_4
vega                      1.4.0                     <pip>
vega-datasets             0.5.0                     <pip>
vincent                   0.4.4                     <pip>
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.32.2                   py37_0
widgetsnbextension        3.4.2                    py37_0
win_inet_pton             1.0.1                    py37_1
win_unicode_console       0.5                      py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4    conda-forge
wordcloud                 1.5.0           py37hfa6e2cd_1000    <unknown>
wrapt                     1.10.11          py37hfa6e2cd_2
xlrd                      1.1.0                      py_2    conda-forge
xlsxwriter                1.1.2                      py_0    conda-forge
xlwings                   0.12.1                   py37_0
xlwt                      1.3.0                      py_1    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.7                    vc14_0  [vc14]  conda-forge
zeromq                    4.2.5                he025d50_1
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge
zope                      1.0                      py37_1
zope.interface            4.5.0            py37hfa6e2cd_0

(base) C:\Users\be>
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

(base) C:\Users\be>conda info
    active environment : base
     active env location : C:\Users\be\Anaconda3
                   shell level : 1
           user config file : C:\Users\be\.condarc
 populated config files : C:\Users\be\.condarc
            conda version : 4.5.11
   conda-build version : 3.16.1
          python version : 3.7.1.final.0
     base environment : C:\Users\be\Anaconda3  (writable)
            channel URLs : https://conda.anaconda.org/conda-forge/win-32
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/r/win-32
                          https://conda.anaconda.org/r/noarch
                          https://repo.anaconda.com/pkgs/main/win-32
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-32
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-32
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-32
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-32
                          https://repo.anaconda.com/pkgs/msys2/noarch
           package cache : C:\Users\be\Anaconda3\pkgs
                                    C:\Users\be\AppData\Local\conda\conda\pkgs
         envs directories : C:\Users\be\Anaconda3\envs
                                    C:\Users\be\AppData\Local\conda\conda\envs
                          C:\Users\be\.conda\envs
               platform : win-32
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.1 Windows/8.1
 Windows/6.3.9600
          administrator : False
             netrc file : None
           offline mode : False

(base) C:\Users\be>
```
</details>

**Comment by amueller** [comment]
Can you please give more details?

**Comment by amueller** [comment]
please edit the post to show the details, not the title.

**Comment by ocefpaf** [comment]
> Issue: I am using window 8.1 version 32-bites.

Conda-forge does not build Win 32-bit and, based on the channel info, looks like you are force installing the 64-bit version there:

```
wordcloud                 1.5.0           py37hfa6e2cd_1000    <unknown>
```
