### ISSUE TITLE
Any plan to add an osx-arm64 build ?

### ISSUE THREAD

**Issue by ivaquero** [conda-forge/wordcloud-feedstock#29]

**Comment by ocefpaf** [comment]
You can send a PR to add it to the migrator here: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt

**Comment by ivaquero** [comment]
Thank you. I'll try.

**Comment by ivaquero** [comment]
PR has merged, see [conda-forge/conda-forge-pinning-feedstock#3098](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3098)
