### ISSUE TITLE
Linux/Windows Python 3.6 builds are missing?

### ISSUE THREAD

**Issue by QuLogic** [conda-forge/wordcloud-feedstock#3]
I think from #2, Python 3.6 packages should have been built. However, looking at the [file list](https://anaconda.org/conda-forge/wordcloud/files), there only appears to be 3.6 packages for macOS.

**Comment by QuLogic** [comment]
This may be because of the `[ci skip]` in the PR title.

**Comment by ocefpaf** [comment]
Fixed in #13
